web/config/routes.rb
Web::Application.routes.draw do
  get "sessions/create"
  get "sessions/destroy"
  root :to => 'opening_pages#welcome'
  match '/about',         to:   'opening_pages#about',      via: 'get'

  match '/sign_in',       to:   'sessions#sign_in',         via: 'get'
  match '/sign_in',       to:   'sessions#create',          via: 'post'
  match '/sign_out',      to:   'sessions#sign_out',        via: 'get'

  match '/sign_up',       to:   'users#new',                via: 'get'
  match '/sign_up',       to:   'users#create',             via: 'post'
  match '/select_artist', to:   'users#select_artist',      via: 'get'
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper_method :current_user, :signed_in?

  def current_user
    TM::Database.db.get_user(TM::Database.db.get_uid_from_sid(session[:tm_session_id]))
  end

  def signed_in?
    session[:tm_session_id] != nil
  end

  protect_from_forgery with: :exception
end

web/app/controllers/opening_pages_controller.rb
class OpeningPagesController < ApplicationController
  def welcome
  end

  def about
  end
end

web/app/controllers/sessions_controller.rb
require 'pry-debugger'

class SessionsController < ApplicationController

  def sign_in

  end

  def create
    result = TM::SignIn.run({ username: params[:username], password: params[:password] })
    if result.success?
      session[:tm_session_id] = result.session_id
      return redirect_to select_artist_path
    else
      flash[:notice] = "something you typed don't smell right"
      return redirect_to sign_in_path
    end
  end

  def sign_out
    TM::SignOut.run({ session_id: session[:session_id] })
    reset_session
    return redirect_to root_path
  end


  def destroy
  end
end

web/app/controllers/users_controller.rb
require 'pry-debugger'

class UsersController < ApplicationController
  def new
  end

  def create
    if params[:password] != params[:password_confirmation]
      flash[:notice] = "Passwords don't match, mf"
      return redirect_to sign_up_path
    end
    result = TM::CreateUser.run({ username: params[:username], password: params[:password] })
    if result.success?
      result = TM::SignIn.run({ username: params[:username], password: params[:password] })
      session[:tm_session_id] = result.session_id
      redirect_to select_artist_path
    elsif result.error == :username_taken
      flash[:notice] = "mf, that username is taken."
      return redirect_to sign_up_path
    end
  end

  def select_artist
    if !signed_in?
      flash[:notice] = "Please sign in"
      redirect_to root_path
    else
      result = TM::GetArtistsByUser.run(current_user.id)
      @artists = result.artists
    end
  end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "BA Tour Manager"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

web/app/helpers/opening_pages_helper.rb
module OpeningPagesHelper
end

web/app/helpers/sessions_helper.rb
module SessionsHelper
end

web/app/helpers/users_helper.rb
module UsersHelper
end

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "BA Tour Manager Pro", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "About",   about_path %></li>
              <% if signed_in? == false %>
                <li><%= link_to "Sign In", sign_in_path %></li>
              <% else %>
                <li><%= link_to "Sign Out", sign_out_path %></li>
              <% end %>
              <% if signed_in? == false %>
                <li><%= link_to "Sign Up", sign_up_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

web/app/views/opening_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us</h1>
<h3>
  This app is designed to keep track of all aspects of an artist's touring life, including:
  </h3>
  <h3>
    <ul>
    <li>Tour Finances (deposits, expenses, booking fees, billing, etc)</li>
    <li>Long-Term Financial Growth</li>
    <li>Per-Market Attendance and Guarantee Data</li>
    <li>Music Charts and Mp3s</li>
  </ul>
</h3>

web/app/views/opening_pages/welcome.html.erb
<div class="center hero-unit">
  <h1>Welcome to BA Tour Manager Pro</h1>

  <h2>
    Welcome to Badass Tour Manager Pro
  </h2>

  <% if flash[:notice] %>
    <h3><%= flash[:notice] %></h3>
  <% end %>

  <%= link_to "Sign Up", sign_up_path, class: "btn btn-large btn-primary" %>
</div>

web/app/views/users/create.html.erb
<h1> your account is created <h1>

web/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
      <% if flash[:notice] %>
        <h2 color="red">
        <%= flash[:notice] %>
        </h2>
      <% end %>

    <%= form_tag signup_path do %>
      <%= label_tag :username %>
      <%= text_field_tag :username %>

      <%= label_tag :password %>
      <%= password_field_tag :password %>

      <%= label_tag :password_confirmation, "Confirmation" %>
      <%= password_field_tag :password_confirmation %>

      <%= submit_tag "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

web/app/views/users/select_artist.html.erb
<h1>Select an Artist</h1>
<div class="center hero-unit">
  <% @artists.each do |artist| %>
    <h2><a href="#"><%= artist.name %> </h2></a></br>
  <% end %>
  <%= link_to "Add Artist", '#', class: "btn btn-large btn-primary" %>
</div>

web/app/views/users/sign_in.html.erb
<% provide(:title, 'Sign In') %>
<h1>Sign In</h1>

<div class="row">
  <div class="span6 offset3">
      <% if flash[:notice] %>
        <h2 color="red">
        <%= flash[:notice] %>
        </h2>
      <% end %>

    <%= form_tag signin_path do %>
      <%= label_tag :username %>
      <%= text_field_tag :username %>

      <%= label_tag :password %>
      <%= password_field_tag :password %>

      <%= submit_tag "Sign In", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

web/app/views/users/sign_up.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
      <% if flash[:notice] %>
        <h2 color="red">
        <%= flash[:notice] %>
        </h2>
      <% end %>

    <%= form_tag sign_up_path do %>
      <%= label_tag :username %>
      <%= text_field_tag :username %>

      <%= label_tag :password %>
      <%= password_field_tag :password %>

      <%= label_tag :password_confirmation, "Confirmation" %>
      <%= password_field_tag :password_confirmation %>

      <%= submit_tag "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>